package group25.Utils;

public enum CrashMode {
    TM_BEFORE_VOTE_REQUEST,
    TM_BEFORE_ANY_VOTE_REPLIES,
    TM_BEFORE_LAST_VOTE_REPLY,
    TM_BEFORE_DECIDING,
    TM_BEFORE_SENDING_DECISION,
    TM_BEFORE_SENDING_LAST_DECISION,
    TM_AFTER_SENDING_ALL_DECISIONS,
    TM_DURING_RECOVERY,

    RM_BEFORE_DECIDING_VOTE,
    RM_AFTER_DECIDING_VOTE,
    RM_AFTER_VOTING,
    RM_AFTER_RECEIVING_DECISION,
    RM_DURING_RECOVERY,

    NO_CRASH,
}